/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00174b",
        "primary-container": "#131b2e",
        "on-tertiary-fixed": "#002114",
        "on-background": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#131b2e",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005137",
        "on-tertiary-container": "#069669",
        "surface-tint": "#565e74",
        "inverse-surface": "#213145",
        "primary": "#000000",
        "tertiary-fixed": "#85f8c4",
        "surface": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#316bf3",
        "tertiary": "#000000",
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#003ea8",
        "outline": "#76777d",
        "on-surface-variant": "#45464d",
        "tertiary-fixed-dim": "#68dba9",
        "inverse-primary": "#bec6e0",
        "on-surface": "#0b1c30",
        "outline-variant": "#c6c6cd",
        "on-primary": "#ffffff",
        "tertiary-container": "#002114",
        "on-error-container": "#93000a",
        "on-primary-container": "#7c839b",
        "secondary": "#0051d5",
        "primary-fixed": "#dae2fd",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "on-secondary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "surface-variant": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#cbdbf5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "headline-sm": ["Geist", "sans-serif"],
        "headline-xl-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "code-sm": ["Geist", "monospace"],
        "headline-xl": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "headline-xl-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "20px", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "code-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "500" }],
        "headline-xl": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
